version: '3.7'

services:

  algo-api:
    build: ./algorithms
    container_name: algo-api
    ports: 
      - 8000:8000
    volumes:
      - ./src:/app/src
    restart: always

  prometheus:
    build: ./prometheus
    ports: 
      - 9090:9090
    restart: always

  pushgateway:
    image: prom/pushgateway
    ports: 
      - 9091:9091
    restart: always

  grafana:
    image: grafana/grafana
    volumes:
      - ./.grafana/data:/var/lib/grafana
    ports: 
      - 3000:3000
    restart: always
  
  loadgen:
    build: ./loadgen
    environment:
      - FRONTEND_ADDR=algo-api:8000
    restart: always
