global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
    monitor: 'algo-api'

scrape_configs:
  - job_name: 'algo-api'

    scrape_interval: 5s

    static_configs:
      - targets: ['pushgateway:9091']
